<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="config.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="config.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetCord" Version="1.0.0-beta.27" />
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-beta.27" />
    <PackageReference Include="NetCord.Hosting.AspNetCore" Version="1.0.0-beta.27" />
    <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.27" />
    <PackageReference Include="NetCord.Services" Version="1.0.0-beta.27" />
    <PackageReference Include="TwitchLib" Version="3.5.3" />
  </ItemGroup>

</Project>
